#!/bin/bash
#Java builder WAR

filename=$(basename "$4")
extension="${filename##*.}"
filename="${filename%.*}"

case "$extension" in

war)  cd $3
      rm *.war
      rm -r $2
      wget $4
      chown -R sandbox:sandbox *.war
      ;;
git)  cd $3
      rm *.war
      cd /home/sandbox/
      rm -r $filename
      git clone $4
      cd $filename
      mvn clean
      mvn package
      cp target/*.war $3
      chown -R sandbox:sandbox $3/*.war
      ;;
esac

stop tomcat
start tomcat

